-- Encargo CREATE TABLE public."Encargo" ( "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Fecha" date, "Entregado" boolean, "IdUsuario" uuid, CONSTRAINT "Encargo_IdUsuario_fkey" FOREIGN KEY ("IdUsuario") REFERENCES public."Usuario"("ID") );

-- Feedback CREATE TABLE public."Feedback" ( "Fecha" date, "IdUsuario" uuid DEFAULT gen_random_uuid(), "Hecho" boolean DEFAULT false, "Comentario" text CHECK (length("Comentario") > 10), PRIMARY KEY ("Fecha","IdUsuario"), CONSTRAINT "Feedback_IdUsuario_fkey" FOREIGN KEY ("IdUsuario") REFERENCES public."Usuario"("ID") );

-- Foto CREATE TABLE public."Foto" ( "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "IdPlanta" bigint, "Link" text UNIQUE, CONSTRAINT "Foto_IdPlanta_fkey" FOREIGN KEY ("IdPlanta") REFERENCES public."Planta"("ID") );

-- Modulo CREATE TABLE public."Modulo" ( "ID" bigint, "IdPlanta" bigint, "comandos" text, "Password" text CHECK (length("Password") >= 10), CONSTRAINT "Modulo_IdPlanta_fkey" FOREIGN KEY ("IdPlanta") REFERENCES public."Planta"("ID") );

-- Planta CREATE TABLE public."Planta" ( "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Nombre" text, "Tipo" text, "Foto" text, "IdAmbiente" bigint, CONSTRAINT "Planta_Tipo_fkey" FOREIGN KEY ("Tipo") REFERENCES public."TipoEspecifico"("Nombre"), CONSTRAINT "Planta_IdAmbiente_fkey" FOREIGN KEY ("IdAmbiente") REFERENCES public."Ambiente"("ID") );

-- Registro CREATE TABLE public."Registro" ( "Temperatura" real, "HumedadAntes" real, "DuracionRiego" real, "HumedadDsp" smallint, "fecha" smallint PRIMARY KEY, "IdPlanta" smallint );

-- TipoEspecifico CREATE TABLE public."TipoEspecifico" ( "ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Nombre" text UNIQUE, "Info" text, "Grupo" text, "Foto" text UNIQUE, "TempMinIdeal" real, "HumedadAtmosferica" smallint, "TempMaxIdeal" real, "HumedadDelSuelo" smallint, "NombreCientifico" text );

-- TipoGrupo CREATE TABLE public."TipoGrupo" ( "ID" smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Nombre" varchar UNIQUE, "Info" text );

-- Usuario CREATE TABLE public."Usuario" ( "ID" uuid DEFAULT gen_random_uuid() PRIMARY KEY, "Password" text, "Email" text UNIQUE, "Direccion" text, "Nombre" text DEFAULT ''::text, "Foto" text );

-- Ambiente CREATE TABLE public."Ambiente" ( "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Temperatura" real, "IdUsuario" uuid, "Nombre" text, CONSTRAINT "Ambiente_IdUsuario_fkey" FOREIGN KEY ("IdUsuario") REFERENCES public."Usuario"("ID") );

-- Notificacion CREATE TABLE public."Notificacion" ( "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "CreatedAt" timestamptz DEFAULT now(), "Idusuario" uuid, "Urgencia" smallint, "IdPlanta" bigint, "Texto" text, CONSTRAINT "Notificacion_Idusuario_fkey" FOREIGN KEY ("Idusuario") REFERENCES public."Usuario"("ID"), CONSTRAINT "Notificacion_IdPlanta_fkey" FOREIGN KEY ("IdPlanta") REFERENCES public."Planta"("ID") );

-- MensajeChatbot CREATE TABLE public."MensajeChatbot" ( "ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "IdUsuario" uuid DEFAULT auth.uid(), "Hora" timestamptz, "Contenido" text, "RemitenteEsUsuario" boolean, "IdPlanta" bigint, "Multimedia" text, CONSTRAINT "MensajeChatbot_IdUsuario_fkey" FOREIGN KEY ("IdUsuario") REFERENCES public."Usuario"("ID"), CONSTRAINT "MensajeChatbot_IdPlanta_fkey" FOREIGN KEY ("IdPlanta") REFERENCES public."Planta"("ID") );